# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('cpu_is_local', models.CharField(max_length=45, primary_key=True, serialize=False, unique=True)),
                ('cpu_consum', models.BooleanField()),
                ('cpu_state_set', models.IntegerField()),
            ],
        ),
    ]
